# Generated by Django 2.1.3 on 2018-12-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pretitle',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Antetítulo'),
        ),
    ]
